### ISSUE TITLE
03_browse_item_detail_view.html 에 PDF Viewer를 삽입한다.

### ISSUE THREAD

**Issue by woonjjang** [sda17dev/sda-prototype#1]
https://sda17dev.github.io/sda-prototype/html/03_browse_item_detail_view.html
https://github.com/sda17dev/sda-prototype/blob/gh-pages/html/03_browse_file_detail_view.html

https://github.com/mozilla/pdf.js/

**Comment by mozodev** [comment]
https://cdnjs.cloudflare.com/ajax/libs/pdf.js/1.8.579/pdf.min.js

**Comment by mozodev** [comment]
https://sda17dev.github.io/sda-prototype/html/03_browse_item_detail_view.html
